// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: custom_payload.proto
// Protobuf C++ Version: 7.35.1

#include "custom_payload.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::edgesim::VehicleMetadata
        {&::_pbi::kDescriptorMethods, &::descriptor_table_custom_5fpayload_2eproto, /* tracker*/ nullptr,},
        // ::edgesim::ControllerCommand
        {&::_pbi::kDescriptorMethods, &::descriptor_table_custom_5fpayload_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace edgesim {
class VehicleMetadata::_Internal {
 public:
  using HasBits = decltype(::std::declval<VehicleMetadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_._has_bits_);
};

constexpr VehicleMetadata::ParseTableT_ VehicleMetadata::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_._has_bits_),
      0, // no _extensions_
      15, 120,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294934528,  // skipmap
      offsetof(ParseTableT_, field_entries),
      15,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::edgesim::VehicleMetadata>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // int32 frame_id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.frame_id_), 3>(),
       {8, 3, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.frame_id_)}},
      // int32 handover_status = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.handover_status_), 4>(),
       {16, 4, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.handover_status_)}},
      // string sensor_path = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 0, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.sensor_path_)}},
      // int64 timestamp_ns = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VehicleMetadata, _impl_.timestamp_ns_), 5>(),
       {32, 5, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.timestamp_ns_)}},
      // double simulated_rssi = 5;
      {::_pbi::TcParser::FastF64S1,
       {41, 6, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.simulated_rssi_)}},
      // int32 task_type = 6;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.task_type_), 7>(),
       {48, 7, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.task_type_)}},
      // string requested_file_id = 7;
      {::_pbi::TcParser::FastUS1,
       {58, 1, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.requested_file_id_)}},
      // int32 file_size_mb = 8;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.file_size_mb_), 8>(),
       {64, 8, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.file_size_mb_)}},
      // int32 sequence_number = 9;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.sequence_number_), 10>(),
       {72, 10, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.sequence_number_)}},
      // bool is_handover_packet = 10;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(VehicleMetadata, _impl_.is_handover_packet_), 11>(),
       {80, 11, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_handover_packet_)}},
      // double vehicle_speed_kmh = 11;
      {::_pbi::TcParser::FastF64S1,
       {89, 9, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.vehicle_speed_kmh_)}},
      // bool is_control_packet = 12;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(VehicleMetadata, _impl_.is_control_packet_), 12>(),
       {96, 12, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_control_packet_)}},
      // int32 continuity_action = 13;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VehicleMetadata, _impl_.continuity_action_), 14>(),
       {104, 14, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.continuity_action_)}},
      // string state_payload = 14;
      {::_pbi::TcParser::FastUS1,
       {114, 2, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.state_payload_)}},
      // bool is_boundary_update = 15;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(VehicleMetadata, _impl_.is_boundary_update_), 13>(),
       {120, 13, 0,
        PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_boundary_update_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 frame_id = 1;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.frame_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 handover_status = 2;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.handover_status_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string sensor_path = 3;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.sensor_path_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int64 timestamp_ns = 4;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.timestamp_ns_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // double simulated_rssi = 5;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.simulated_rssi_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
      // int32 task_type = 6;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.task_type_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string requested_file_id = 7;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.requested_file_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int32 file_size_mb = 8;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.file_size_mb_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 sequence_number = 9;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.sequence_number_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // bool is_handover_packet = 10;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_handover_packet_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // double vehicle_speed_kmh = 11;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.vehicle_speed_kmh_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
      // bool is_control_packet = 12;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_control_packet_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // int32 continuity_action = 13;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.continuity_action_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string state_payload = 14;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.state_payload_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bool is_boundary_update = 15;
      {PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.is_boundary_update_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    }},
    // no aux_entries
    {{
      "\27\0\0\13\0\0\0\21\0\0\0\0\0\0\15\0"
      "edgesim.VehicleMetadata"
      "sensor_path"
      "requested_file_id"
      "state_payload"
    }},
  };
}


inline constexpr VehicleMetadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sensor_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requested_file_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        state_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        frame_id_{0},
        handover_status_{0},
        timestamp_ns_{::int64_t{0}},
        simulated_rssi_{0},
        task_type_{0},
        file_size_mb_{0},
        vehicle_speed_kmh_{0},
        sequence_number_{0},
        is_handover_packet_{false},
        is_control_packet_{false},
        is_boundary_update_{false},
        continuity_action_{0} {}

template <typename>
constexpr VehicleMetadata::VehicleMetadata(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL VehicleMetadata::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VehicleMetadata(arena);
}
constexpr auto VehicleMetadata::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VehicleMetadata), alignof(VehicleMetadata));
}
constexpr auto VehicleMetadata::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VehicleMetadata::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VehicleMetadata>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VehicleMetadata::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VehicleMetadata>(), &VehicleMetadata::ByteSizeLong,
              &VehicleMetadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_custom_5fpayload_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct VehicleMetadataGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VehicleMetadataGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VehicleMetadata_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VehicleMetadata::InternalGenerateClassData_(
            _default, &VehicleMetadata_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VehicleMetadata>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VehicleMetadataGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VehicleMetadata _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VehicleMetadata>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VehicleMetadataGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VehicleMetadataGlobalsTypeInternal VehicleMetadata_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VehicleMetadata_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VehicleMetadata_globals_.GetClassData();
#else
  return VehicleMetadata_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class ControllerCommand::_Internal {
 public:
  using HasBits = decltype(::std::declval<ControllerCommand>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_._has_bits_);
};

constexpr ControllerCommand::ParseTableT_ ControllerCommand::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::edgesim::ControllerCommand>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string command = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.command_)}},
      // double value = 2;
      {::_pbi::TcParser::FastF64S1,
       {17, 2, 0,
        PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.value_)}},
      // string fault_name = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 1, 0,
        PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.fault_name_)}},
      // bool enable = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ControllerCommand, _impl_.enable_), 4>(),
       {32, 4, 0,
        PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.enable_)}},
      // int64 timestamp_ns = 5;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ControllerCommand, _impl_.timestamp_ns_), 3>(),
       {40, 3, 0,
        PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.timestamp_ns_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // string command = 1;
      {PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.command_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // double value = 2;
      {PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.value_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
      // string fault_name = 3;
      {PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.fault_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bool enable = 4;
      {PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.enable_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // int64 timestamp_ns = 5;
      {PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.timestamp_ns_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
      "\31\7\0\12\0\0\0\0"
      "edgesim.ControllerCommand"
      "command"
      "fault_name"
    }},
  };
}


inline constexpr ControllerCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        command_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fault_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_{0},
        timestamp_ns_{::int64_t{0}},
        enable_{false} {}

template <typename>
constexpr ControllerCommand::ControllerCommand(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL ControllerCommand::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ControllerCommand(arena);
}
constexpr auto ControllerCommand::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ControllerCommand), alignof(ControllerCommand));
}
constexpr auto ControllerCommand::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &ControllerCommand::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ControllerCommand>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ControllerCommand::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ControllerCommand>(), &ControllerCommand::ByteSizeLong,
              &ControllerCommand::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_custom_5fpayload_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct ControllerCommandGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr ControllerCommandGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 ControllerCommand_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(ControllerCommand::InternalGenerateClassData_(
            _default, &ControllerCommand_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<ControllerCommand>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~ControllerCommandGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) ControllerCommand _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<ControllerCommand>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(ControllerCommandGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST ControllerCommandGlobalsTypeInternal ControllerCommand_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* ControllerCommand_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ControllerCommand_globals_.GetClassData();
#else
  return ControllerCommand_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace edgesim
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_custom_5fpayload_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_custom_5fpayload_2eproto = nullptr;
const ::uint32_t
    TableStruct_custom_5fpayload_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_._has_bits_),
        18, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.frame_id_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.handover_status_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.sensor_path_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.timestamp_ns_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.simulated_rssi_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.task_type_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.requested_file_id_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.file_size_mb_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.sequence_number_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.is_handover_packet_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.vehicle_speed_kmh_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.is_control_packet_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.continuity_action_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.state_payload_),
        PROTOBUF_FIELD_OFFSET(::edgesim::VehicleMetadata, _impl_.is_boundary_update_),
        3,
        4,
        0,
        5,
        6,
        7,
        1,
        8,
        10,
        11,
        9,
        12,
        14,
        2,
        13,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_.command_),
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_.fault_name_),
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_.enable_),
        PROTOBUF_FIELD_OFFSET(::edgesim::ControllerCommand, _impl_.timestamp_ns_),
        0,
        2,
        1,
        4,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::edgesim::VehicleMetadata)},
        {33, sizeof(::edgesim::ControllerCommand)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::edgesim::VehicleMetadata_globals_,
        &::edgesim::ControllerCommand_globals_,
};
const char descriptor_table_protodef_custom_5fpayload_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024custom_payload.proto\022\007edgesim\"\374\002\n\017Vehi"
    "cleMetadata\022\020\n\010frame_id\030\001 \001(\005\022\027\n\017handove"
    "r_status\030\002 \001(\005\022\023\n\013sensor_path\030\003 \001(\t\022\024\n\014t"
    "imestamp_ns\030\004 \001(\003\022\026\n\016simulated_rssi\030\005 \001("
    "\001\022\021\n\ttask_type\030\006 \001(\005\022\031\n\021requested_file_i"
    "d\030\007 \001(\t\022\024\n\014file_size_mb\030\010 \001(\005\022\027\n\017sequenc"
    "e_number\030\t \001(\005\022\032\n\022is_handover_packet\030\n \001"
    "(\010\022\031\n\021vehicle_speed_kmh\030\013 \001(\001\022\031\n\021is_cont"
    "rol_packet\030\014 \001(\010\022\031\n\021continuity_action\030\r "
    "\001(\005\022\025\n\rstate_payload\030\016 \001(\t\022\032\n\022is_boundar"
    "y_update\030\017 \001(\010\"m\n\021ControllerCommand\022\017\n\007c"
    "ommand\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\022\022\n\nfault_nam"
    "e\030\003 \001(\t\022\016\n\006enable\030\004 \001(\010\022\024\n\014timestamp_ns\030"
    "\005 \001(\003b\006proto3"
};
static ::absl::once_flag descriptor_table_custom_5fpayload_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_custom_5fpayload_2eproto = {
    false,
    false,
    533,
    descriptor_table_protodef_custom_5fpayload_2eproto,
    "custom_payload.proto",
    &descriptor_table_custom_5fpayload_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_custom_5fpayload_2eproto::offsets,
    file_level_enum_descriptors_custom_5fpayload_2eproto,
    file_level_service_descriptors_custom_5fpayload_2eproto,
};
namespace edgesim {
// ===================================================================

VehicleMetadata::VehicleMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VehicleMetadata_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:edgesim.VehicleMetadata)
}
PROTOBUF_NDEBUG_INLINE VehicleMetadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::edgesim::VehicleMetadata& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sensor_path_(arena, from.sensor_path_),
        requested_file_id_(arena, from.requested_file_id_),
        state_payload_(arena, from.state_payload_) {}

VehicleMetadata::VehicleMetadata(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VehicleMetadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VehicleMetadata_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VehicleMetadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, frame_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, frame_id_),
           offsetof(Impl_, continuity_action_) -
               offsetof(Impl_, frame_id_) +
               sizeof(Impl_::continuity_action_));

  // @@protoc_insertion_point(copy_constructor:edgesim.VehicleMetadata)
}
PROTOBUF_NDEBUG_INLINE VehicleMetadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sensor_path_(arena),
        requested_file_id_(arena),
        state_payload_(arena) {}

inline void VehicleMetadata::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, frame_id_),
           0,
           offsetof(Impl_, continuity_action_) -
               offsetof(Impl_, frame_id_) +
               sizeof(Impl_::continuity_action_));
}
VehicleMetadata::~VehicleMetadata() {
  // @@protoc_insertion_point(destructor:edgesim.VehicleMetadata)
  SharedDtor(*this);
}
inline void VehicleMetadata::SharedDtor(MessageLite& self) {
  VehicleMetadata& this_ = static_cast<VehicleMetadata&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sensor_path_.Destroy();
  this_._impl_.requested_file_id_.Destroy();
  this_._impl_.state_payload_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VehicleMetadata_class_data_ =
        VehicleMetadata::InternalGenerateClassData_(VehicleMetadata_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VehicleMetadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VehicleMetadata_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VehicleMetadata_class_data_.tc_table);
  return VehicleMetadata_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VehicleMetadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VehicleMetadata_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&VehicleMetadata_globals_));
  return VehicleMetadata_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VehicleMetadata::ParseTableT_
    VehicleMetadata::_table_ =
        VehicleMetadata::InternalGenerateParseTable_(VehicleMetadata_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void VehicleMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:edgesim.VehicleMetadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.sensor_path_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.requested_file_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.state_payload_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f8U)) {
    ::memset(&_impl_.frame_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.task_type_) -
        reinterpret_cast<char*>(&_impl_.frame_id_)) + sizeof(_impl_.task_type_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    ::memset(&_impl_.file_size_mb_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.continuity_action_) -
        reinterpret_cast<char*>(&_impl_.file_size_mb_)) + sizeof(_impl_.continuity_action_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VehicleMetadata::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VehicleMetadata& this_ = static_cast<const VehicleMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VehicleMetadata::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VehicleMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:edgesim.VehicleMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 frame_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_frame_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_frame_id(), target);
    }
  }

  // int32 handover_status = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_handover_status() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_handover_status(), target);
    }
  }

  // string sensor_path = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_sensor_path().empty()) {
      const ::std::string& _s = this_._internal_sensor_path();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "edgesim.VehicleMetadata.sensor_path");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // int64 timestamp_ns = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_timestamp_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_timestamp_ns(), target);
    }
  }

  // double simulated_rssi = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_simulated_rssi()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_simulated_rssi(), target);
    }
  }

  // int32 task_type = 6;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_task_type() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_task_type(), target);
    }
  }

  // string requested_file_id = 7;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_requested_file_id().empty()) {
      const ::std::string& _s = this_._internal_requested_file_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "edgesim.VehicleMetadata.requested_file_id");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // int32 file_size_mb = 8;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_file_size_mb() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<8>(
              stream, this_._internal_file_size_mb(), target);
    }
  }

  // int32 sequence_number = 9;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_sequence_number() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<9>(
              stream, this_._internal_sequence_number(), target);
    }
  }

  // bool is_handover_packet = 10;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (this_._internal_is_handover_packet() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          10, this_._internal_is_handover_packet(), target);
    }
  }

  // double vehicle_speed_kmh = 11;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_vehicle_speed_kmh()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          11, this_._internal_vehicle_speed_kmh(), target);
    }
  }

  // bool is_control_packet = 12;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (this_._internal_is_control_packet() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          12, this_._internal_is_control_packet(), target);
    }
  }

  // int32 continuity_action = 13;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    if (this_._internal_continuity_action() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<13>(
              stream, this_._internal_continuity_action(), target);
    }
  }

  // string state_payload = 14;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_state_payload().empty()) {
      const ::std::string& _s = this_._internal_state_payload();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "edgesim.VehicleMetadata.state_payload");
      target = stream->WriteStringMaybeAliased(14, _s, target);
    }
  }

  // bool is_boundary_update = 15;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (this_._internal_is_boundary_update() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          15, this_._internal_is_boundary_update(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:edgesim.VehicleMetadata)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VehicleMetadata::ByteSizeLong(const MessageLite& base) {
  const VehicleMetadata& this_ = static_cast<const VehicleMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VehicleMetadata::ByteSizeLong() const {
  const VehicleMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:edgesim.VehicleMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string sensor_path = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_sensor_path().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sensor_path());
      }
    }
    // string requested_file_id = 7;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_requested_file_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_requested_file_id());
      }
    }
    // string state_payload = 14;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_state_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_state_payload());
      }
    }
    // int32 frame_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_frame_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_frame_id());
      }
    }
    // int32 handover_status = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_handover_status() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_handover_status());
      }
    }
    // int64 timestamp_ns = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp_ns());
      }
    }
    // double simulated_rssi = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_simulated_rssi()) != 0) {
        total_size += 9;
      }
    }
    // int32 task_type = 6;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_task_type() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_task_type());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    // int32 file_size_mb = 8;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_file_size_mb() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_file_size_mb());
      }
    }
    // double vehicle_speed_kmh = 11;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_vehicle_speed_kmh()) != 0) {
        total_size += 9;
      }
    }
    // int32 sequence_number = 9;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_sequence_number() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_sequence_number());
      }
    }
    // bool is_handover_packet = 10;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (this_._internal_is_handover_packet() != 0) {
        total_size += 2;
      }
    }
    // bool is_control_packet = 12;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (this_._internal_is_control_packet() != 0) {
        total_size += 2;
      }
    }
    // bool is_boundary_update = 15;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (this_._internal_is_boundary_update() != 0) {
        total_size += 2;
      }
    }
    // int32 continuity_action = 13;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (this_._internal_continuity_action() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_continuity_action());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VehicleMetadata::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<VehicleMetadata*>(&to_msg);
  auto& from = static_cast<const VehicleMetadata&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:edgesim.VehicleMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_sensor_path().empty()) {
        _this->_internal_set_sensor_path(from._internal_sensor_path());
      } else {
        if (_this->_impl_.sensor_path_.IsDefault()) {
          _this->_internal_set_sensor_path("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_requested_file_id().empty()) {
        _this->_internal_set_requested_file_id(from._internal_requested_file_id());
      } else {
        if (_this->_impl_.requested_file_id_.IsDefault()) {
          _this->_internal_set_requested_file_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_state_payload().empty()) {
        _this->_internal_set_state_payload(from._internal_state_payload());
      } else {
        if (_this->_impl_.state_payload_.IsDefault()) {
          _this->_internal_set_state_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_frame_id() != 0) {
        _this->_impl_.frame_id_ = from._impl_.frame_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_handover_status() != 0) {
        _this->_impl_.handover_status_ = from._impl_.handover_status_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_timestamp_ns() != 0) {
        _this->_impl_.timestamp_ns_ = from._impl_.timestamp_ns_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_simulated_rssi()) != 0) {
        _this->_impl_.simulated_rssi_ = from._impl_.simulated_rssi_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_task_type() != 0) {
        _this->_impl_.task_type_ = from._impl_.task_type_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_file_size_mb() != 0) {
        _this->_impl_.file_size_mb_ = from._impl_.file_size_mb_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_vehicle_speed_kmh()) != 0) {
        _this->_impl_.vehicle_speed_kmh_ = from._impl_.vehicle_speed_kmh_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_sequence_number() != 0) {
        _this->_impl_.sequence_number_ = from._impl_.sequence_number_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (from._internal_is_handover_packet() != 0) {
        _this->_impl_.is_handover_packet_ = from._impl_.is_handover_packet_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (from._internal_is_control_packet() != 0) {
        _this->_impl_.is_control_packet_ = from._impl_.is_control_packet_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (from._internal_is_boundary_update() != 0) {
        _this->_impl_.is_boundary_update_ = from._impl_.is_boundary_update_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (from._internal_continuity_action() != 0) {
        _this->_impl_.continuity_action_ = from._impl_.continuity_action_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void VehicleMetadata::CopyFrom(const VehicleMetadata& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:edgesim.VehicleMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VehicleMetadata::InternalSwap(VehicleMetadata* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sensor_path_, &other->_impl_.sensor_path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.requested_file_id_, &other->_impl_.requested_file_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.state_payload_, &other->_impl_.state_payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.continuity_action_)
      + sizeof(VehicleMetadata::_impl_.continuity_action_)
      - PROTOBUF_FIELD_OFFSET(VehicleMetadata, _impl_.frame_id_)>(
          reinterpret_cast<char*>(&_impl_.frame_id_),
          reinterpret_cast<char*>(&other->_impl_.frame_id_));
}

::google::protobuf::Metadata VehicleMetadata::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

ControllerCommand::ControllerCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ControllerCommand_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:edgesim.ControllerCommand)
}
PROTOBUF_NDEBUG_INLINE ControllerCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::edgesim::ControllerCommand& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        command_(arena, from.command_),
        fault_name_(arena, from.fault_name_) {}

ControllerCommand::ControllerCommand(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ControllerCommand& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ControllerCommand_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ControllerCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, value_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, value_),
           offsetof(Impl_, enable_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::enable_));

  // @@protoc_insertion_point(copy_constructor:edgesim.ControllerCommand)
}
PROTOBUF_NDEBUG_INLINE ControllerCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        command_(arena),
        fault_name_(arena) {}

inline void ControllerCommand::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, value_),
           0,
           offsetof(Impl_, enable_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::enable_));
}
ControllerCommand::~ControllerCommand() {
  // @@protoc_insertion_point(destructor:edgesim.ControllerCommand)
  SharedDtor(*this);
}
inline void ControllerCommand::SharedDtor(MessageLite& self) {
  ControllerCommand& this_ = static_cast<ControllerCommand&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.command_.Destroy();
  this_._impl_.fault_name_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ControllerCommand_class_data_ =
        ControllerCommand::InternalGenerateClassData_(ControllerCommand_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ControllerCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ControllerCommand_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ControllerCommand_class_data_.tc_table);
  return ControllerCommand_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ControllerCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ControllerCommand_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&ControllerCommand_globals_));
  return ControllerCommand_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ControllerCommand::ParseTableT_
    ControllerCommand::_table_ =
        ControllerCommand::InternalGenerateParseTable_(ControllerCommand_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void ControllerCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:edgesim.ControllerCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.command_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.fault_name_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.value_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.enable_) -
        reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.enable_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ControllerCommand::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ControllerCommand& this_ = static_cast<const ControllerCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ControllerCommand::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ControllerCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:edgesim.ControllerCommand)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string command = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_command().empty()) {
      const ::std::string& _s = this_._internal_command();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "edgesim.ControllerCommand.command");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // double value = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_value(), target);
    }
  }

  // string fault_name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_fault_name().empty()) {
      const ::std::string& _s = this_._internal_fault_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "edgesim.ControllerCommand.fault_name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bool enable = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_enable() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_enable(), target);
    }
  }

  // int64 timestamp_ns = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_timestamp_ns() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
              stream, this_._internal_timestamp_ns(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:edgesim.ControllerCommand)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ControllerCommand::ByteSizeLong(const MessageLite& base) {
  const ControllerCommand& this_ = static_cast<const ControllerCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ControllerCommand::ByteSizeLong() const {
  const ControllerCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:edgesim.ControllerCommand)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string command = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_command().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_command());
      }
    }
    // string fault_name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_fault_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fault_name());
      }
    }
    // double value = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
        total_size += 9;
      }
    }
    // int64 timestamp_ns = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_timestamp_ns() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp_ns());
      }
    }
    // bool enable = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_enable() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ControllerCommand::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<ControllerCommand*>(&to_msg);
  auto& from = static_cast<const ControllerCommand&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:edgesim.ControllerCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_command().empty()) {
        _this->_internal_set_command(from._internal_command());
      } else {
        if (_this->_impl_.command_.IsDefault()) {
          _this->_internal_set_command("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_fault_name().empty()) {
        _this->_internal_set_fault_name(from._internal_fault_name());
      } else {
        if (_this->_impl_.fault_name_.IsDefault()) {
          _this->_internal_set_fault_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_value()) != 0) {
        _this->_impl_.value_ = from._impl_.value_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_timestamp_ns() != 0) {
        _this->_impl_.timestamp_ns_ = from._impl_.timestamp_ns_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_enable() != 0) {
        _this->_impl_.enable_ = from._impl_.enable_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ControllerCommand::CopyFrom(const ControllerCommand& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:edgesim.ControllerCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ControllerCommand::InternalSwap(ControllerCommand* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.command_, &other->_impl_.command_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fault_name_, &other->_impl_.fault_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.enable_)
      + sizeof(ControllerCommand::_impl_.enable_)
      - PROTOBUF_FIELD_OFFSET(ControllerCommand, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::google::protobuf::Metadata ControllerCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace edgesim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_custom_5fpayload_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
