// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: custom_payload.proto
// Protobuf C++ Version: 7.35.1

#ifndef custom_5fpayload_2eproto_2epb_2eh
#define custom_5fpayload_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_custom_5fpayload_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_custom_5fpayload_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_custom_5fpayload_2eproto;
}  // extern "C"
namespace edgesim {
class ControllerCommand;
struct ControllerCommandGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern ControllerCommandGlobalsTypeInternal ControllerCommand_globals_;
extern const ::google::protobuf::internal::ClassDataFull ControllerCommand_class_data_;
#else
extern const ControllerCommandGlobalsTypeInternal ControllerCommand_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class VehicleMetadata;
struct VehicleMetadataGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VehicleMetadataGlobalsTypeInternal VehicleMetadata_globals_;
extern const ::google::protobuf::internal::ClassDataFull VehicleMetadata_class_data_;
#else
extern const VehicleMetadataGlobalsTypeInternal VehicleMetadata_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace edgesim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace edgesim {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VehicleMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:edgesim.VehicleMetadata) */ {
 public:
  inline VehicleMetadata() : VehicleMetadata(nullptr) {}
  ~VehicleMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VehicleMetadata* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VehicleMetadata));
  }
#endif

  template <typename = void>
  explicit constexpr VehicleMetadata(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline VehicleMetadata(const VehicleMetadata& from) : VehicleMetadata(nullptr, from) {}
  inline VehicleMetadata(VehicleMetadata&& from) noexcept : VehicleMetadata(nullptr, ::std::move(from)) {}
  inline VehicleMetadata& operator=(const VehicleMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline VehicleMetadata& operator=(VehicleMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const VehicleMetadata& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<VehicleMetadata>(&VehicleMetadata_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VehicleMetadata& a, VehicleMetadata& b) { a.Swap(&b); }
  inline void Swap(VehicleMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VehicleMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] VehicleMetadata* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VehicleMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VehicleMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VehicleMetadata& from) { VehicleMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VehicleMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "edgesim.VehicleMetadata"; }

  explicit VehicleMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VehicleMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VehicleMetadata& from);
  VehicleMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VehicleMetadata&& from) noexcept
      : VehicleMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSensorPathFieldNumber = 3,
    kRequestedFileIdFieldNumber = 7,
    kStatePayloadFieldNumber = 14,
    kFrameIdFieldNumber = 1,
    kHandoverStatusFieldNumber = 2,
    kTimestampNsFieldNumber = 4,
    kSimulatedRssiFieldNumber = 5,
    kTaskTypeFieldNumber = 6,
    kFileSizeMbFieldNumber = 8,
    kVehicleSpeedKmhFieldNumber = 11,
    kSequenceNumberFieldNumber = 9,
    kIsHandoverPacketFieldNumber = 10,
    kIsControlPacketFieldNumber = 12,
    kIsBoundaryUpdateFieldNumber = 15,
    kContinuityActionFieldNumber = 13,
  };
  // string sensor_path = 3;
  void clear_sensor_path() ;
  [[nodiscard]] const ::std::string& sensor_path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sensor_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sensor_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sensor_path();
  void set_allocated_sensor_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sensor_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sensor_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sensor_path();

  public:
  // string requested_file_id = 7;
  void clear_requested_file_id() ;
  [[nodiscard]] const ::std::string& requested_file_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_requested_file_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_requested_file_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_requested_file_id();
  void set_allocated_requested_file_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_requested_file_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_requested_file_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_requested_file_id();

  public:
  // string state_payload = 14;
  void clear_state_payload() ;
  [[nodiscard]] const ::std::string& state_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_state_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_state_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_state_payload();
  void set_allocated_state_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_state_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_state_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_state_payload();

  public:
  // int32 frame_id = 1;
  void clear_frame_id() ;
  [[nodiscard]] ::int32_t frame_id() const;
  void set_frame_id(::int32_t value);

  private:
  ::int32_t _internal_frame_id() const;
  void _internal_set_frame_id(::int32_t value);

  public:
  // int32 handover_status = 2;
  void clear_handover_status() ;
  [[nodiscard]] ::int32_t handover_status() const;
  void set_handover_status(::int32_t value);

  private:
  ::int32_t _internal_handover_status() const;
  void _internal_set_handover_status(::int32_t value);

  public:
  // int64 timestamp_ns = 4;
  void clear_timestamp_ns() ;
  [[nodiscard]] ::int64_t timestamp_ns() const;
  void set_timestamp_ns(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::int64_t value);

  public:
  // double simulated_rssi = 5;
  void clear_simulated_rssi() ;
  [[nodiscard]] double simulated_rssi() const;
  void set_simulated_rssi(double value);

  private:
  double _internal_simulated_rssi() const;
  void _internal_set_simulated_rssi(double value);

  public:
  // int32 task_type = 6;
  void clear_task_type() ;
  [[nodiscard]] ::int32_t task_type() const;
  void set_task_type(::int32_t value);

  private:
  ::int32_t _internal_task_type() const;
  void _internal_set_task_type(::int32_t value);

  public:
  // int32 file_size_mb = 8;
  void clear_file_size_mb() ;
  [[nodiscard]] ::int32_t file_size_mb() const;
  void set_file_size_mb(::int32_t value);

  private:
  ::int32_t _internal_file_size_mb() const;
  void _internal_set_file_size_mb(::int32_t value);

  public:
  // double vehicle_speed_kmh = 11;
  void clear_vehicle_speed_kmh() ;
  [[nodiscard]] double vehicle_speed_kmh() const;
  void set_vehicle_speed_kmh(double value);

  private:
  double _internal_vehicle_speed_kmh() const;
  void _internal_set_vehicle_speed_kmh(double value);

  public:
  // int32 sequence_number = 9;
  void clear_sequence_number() ;
  [[nodiscard]] ::int32_t sequence_number() const;
  void set_sequence_number(::int32_t value);

  private:
  ::int32_t _internal_sequence_number() const;
  void _internal_set_sequence_number(::int32_t value);

  public:
  // bool is_handover_packet = 10;
  void clear_is_handover_packet() ;
  [[nodiscard]] bool is_handover_packet() const;
  void set_is_handover_packet(bool value);

  private:
  bool _internal_is_handover_packet() const;
  void _internal_set_is_handover_packet(bool value);

  public:
  // bool is_control_packet = 12;
  void clear_is_control_packet() ;
  [[nodiscard]] bool is_control_packet() const;
  void set_is_control_packet(bool value);

  private:
  bool _internal_is_control_packet() const;
  void _internal_set_is_control_packet(bool value);

  public:
  // bool is_boundary_update = 15;
  void clear_is_boundary_update() ;
  [[nodiscard]] bool is_boundary_update() const;
  void set_is_boundary_update(bool value);

  private:
  bool _internal_is_boundary_update() const;
  void _internal_set_is_boundary_update(bool value);

  public:
  // int32 continuity_action = 13;
  void clear_continuity_action() ;
  [[nodiscard]] ::int32_t continuity_action() const;
  void set_continuity_action(::int32_t value);

  private:
  ::int32_t _internal_continuity_action() const;
  void _internal_set_continuity_action(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:edgesim.VehicleMetadata)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 15,
                          0, 81,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VehicleMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sensor_path_;
    ::google::protobuf::internal::ArenaStringPtr requested_file_id_;
    ::google::protobuf::internal::ArenaStringPtr state_payload_;
    ::int32_t frame_id_;
    ::int32_t handover_status_;
    ::int64_t timestamp_ns_;
    double simulated_rssi_;
    ::int32_t task_type_;
    ::int32_t file_size_mb_;
    double vehicle_speed_kmh_;
    ::int32_t sequence_number_;
    bool is_handover_packet_;
    bool is_control_packet_;
    bool is_boundary_update_;
    ::int32_t continuity_action_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_custom_5fpayload_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ControllerCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:edgesim.ControllerCommand) */ {
 public:
  inline ControllerCommand() : ControllerCommand(nullptr) {}
  ~ControllerCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ControllerCommand* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ControllerCommand));
  }
#endif

  template <typename = void>
  explicit constexpr ControllerCommand(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline ControllerCommand(const ControllerCommand& from) : ControllerCommand(nullptr, from) {}
  inline ControllerCommand(ControllerCommand&& from) noexcept : ControllerCommand(nullptr, ::std::move(from)) {}
  inline ControllerCommand& operator=(const ControllerCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControllerCommand& operator=(ControllerCommand&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ControllerCommand& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<ControllerCommand>(&ControllerCommand_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ControllerCommand& a, ControllerCommand& b) { a.Swap(&b); }
  inline void Swap(ControllerCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControllerCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ControllerCommand* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ControllerCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControllerCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ControllerCommand& from) { ControllerCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ControllerCommand* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "edgesim.ControllerCommand"; }

  explicit ControllerCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ControllerCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ControllerCommand& from);
  ControllerCommand(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ControllerCommand&& from) noexcept
      : ControllerCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandFieldNumber = 1,
    kFaultNameFieldNumber = 3,
    kValueFieldNumber = 2,
    kTimestampNsFieldNumber = 5,
    kEnableFieldNumber = 4,
  };
  // string command = 1;
  void clear_command() ;
  [[nodiscard]] const ::std::string& command() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_command(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_command();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_command();
  void set_allocated_command(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_command() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_command(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_command();

  public:
  // string fault_name = 3;
  void clear_fault_name() ;
  [[nodiscard]] const ::std::string& fault_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fault_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fault_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fault_name();
  void set_allocated_fault_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fault_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fault_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fault_name();

  public:
  // double value = 2;
  void clear_value() ;
  [[nodiscard]] double value() const;
  void set_value(double value);

  private:
  double _internal_value() const;
  void _internal_set_value(double value);

  public:
  // int64 timestamp_ns = 5;
  void clear_timestamp_ns() ;
  [[nodiscard]] ::int64_t timestamp_ns() const;
  void set_timestamp_ns(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::int64_t value);

  public:
  // bool enable = 4;
  void clear_enable() ;
  [[nodiscard]] bool enable() const;
  void set_enable(bool value);

  private:
  bool _internal_enable() const;
  void _internal_set_enable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:edgesim.ControllerCommand)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          0, 51,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ControllerCommand& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr command_;
    ::google::protobuf::internal::ArenaStringPtr fault_name_;
    double value_;
    ::int64_t timestamp_ns_;
    bool enable_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_custom_5fpayload_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VehicleMetadata

// int32 frame_id = 1;
inline void VehicleMetadata::clear_frame_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int32_t VehicleMetadata::frame_id() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.frame_id)
  return _internal_frame_id();
}
inline void VehicleMetadata::set_frame_id(::int32_t value) {
  _internal_set_frame_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.frame_id)
}
inline ::int32_t VehicleMetadata::_internal_frame_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.frame_id_;
}
inline void VehicleMetadata::_internal_set_frame_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frame_id_ = value;
}

// int32 handover_status = 2;
inline void VehicleMetadata::clear_handover_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.handover_status_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t VehicleMetadata::handover_status() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.handover_status)
  return _internal_handover_status();
}
inline void VehicleMetadata::set_handover_status(::int32_t value) {
  _internal_set_handover_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.handover_status)
}
inline ::int32_t VehicleMetadata::_internal_handover_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.handover_status_;
}
inline void VehicleMetadata::_internal_set_handover_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.handover_status_ = value;
}

// string sensor_path = 3;
inline void VehicleMetadata::clear_sensor_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sensor_path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& VehicleMetadata::sensor_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.sensor_path)
  return _internal_sensor_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VehicleMetadata::set_sensor_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sensor_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.sensor_path)
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::mutable_sensor_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sensor_path();
  // @@protoc_insertion_point(field_mutable:edgesim.VehicleMetadata.sensor_path)
  return _s;
}
inline const ::std::string& VehicleMetadata::_internal_sensor_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sensor_path_.Get();
}
inline void VehicleMetadata::_internal_set_sensor_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sensor_path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::_internal_mutable_sensor_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sensor_path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VehicleMetadata::release_sensor_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:edgesim.VehicleMetadata.sensor_path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sensor_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sensor_path_.Set("", GetArena());
  }
  return released;
}
inline void VehicleMetadata::set_allocated_sensor_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sensor_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sensor_path_.IsDefault()) {
    _impl_.sensor_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:edgesim.VehicleMetadata.sensor_path)
}

// int64 timestamp_ns = 4;
inline void VehicleMetadata::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int64_t VehicleMetadata::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void VehicleMetadata::set_timestamp_ns(::int64_t value) {
  _internal_set_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.timestamp_ns)
}
inline ::int64_t VehicleMetadata::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void VehicleMetadata::_internal_set_timestamp_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

// double simulated_rssi = 5;
inline void VehicleMetadata::clear_simulated_rssi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulated_rssi_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline double VehicleMetadata::simulated_rssi() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.simulated_rssi)
  return _internal_simulated_rssi();
}
inline void VehicleMetadata::set_simulated_rssi(double value) {
  _internal_set_simulated_rssi(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.simulated_rssi)
}
inline double VehicleMetadata::_internal_simulated_rssi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.simulated_rssi_;
}
inline void VehicleMetadata::_internal_set_simulated_rssi(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulated_rssi_ = value;
}

// int32 task_type = 6;
inline void VehicleMetadata::clear_task_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::int32_t VehicleMetadata::task_type() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.task_type)
  return _internal_task_type();
}
inline void VehicleMetadata::set_task_type(::int32_t value) {
  _internal_set_task_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.task_type)
}
inline ::int32_t VehicleMetadata::_internal_task_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.task_type_;
}
inline void VehicleMetadata::_internal_set_task_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_type_ = value;
}

// string requested_file_id = 7;
inline void VehicleMetadata::clear_requested_file_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requested_file_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& VehicleMetadata::requested_file_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.requested_file_id)
  return _internal_requested_file_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VehicleMetadata::set_requested_file_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.requested_file_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.requested_file_id)
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::mutable_requested_file_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_requested_file_id();
  // @@protoc_insertion_point(field_mutable:edgesim.VehicleMetadata.requested_file_id)
  return _s;
}
inline const ::std::string& VehicleMetadata::_internal_requested_file_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requested_file_id_.Get();
}
inline void VehicleMetadata::_internal_set_requested_file_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requested_file_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::_internal_mutable_requested_file_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.requested_file_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VehicleMetadata::release_requested_file_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:edgesim.VehicleMetadata.requested_file_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.requested_file_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.requested_file_id_.Set("", GetArena());
  }
  return released;
}
inline void VehicleMetadata::set_allocated_requested_file_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.requested_file_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.requested_file_id_.IsDefault()) {
    _impl_.requested_file_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:edgesim.VehicleMetadata.requested_file_id)
}

// int32 file_size_mb = 8;
inline void VehicleMetadata::clear_file_size_mb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_mb_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline ::int32_t VehicleMetadata::file_size_mb() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.file_size_mb)
  return _internal_file_size_mb();
}
inline void VehicleMetadata::set_file_size_mb(::int32_t value) {
  _internal_set_file_size_mb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.file_size_mb)
}
inline ::int32_t VehicleMetadata::_internal_file_size_mb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_size_mb_;
}
inline void VehicleMetadata::_internal_set_file_size_mb(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_mb_ = value;
}

// int32 sequence_number = 9;
inline void VehicleMetadata::clear_sequence_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000400U);
}
inline ::int32_t VehicleMetadata::sequence_number() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.sequence_number)
  return _internal_sequence_number();
}
inline void VehicleMetadata::set_sequence_number(::int32_t value) {
  _internal_set_sequence_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.sequence_number)
}
inline ::int32_t VehicleMetadata::_internal_sequence_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_number_;
}
inline void VehicleMetadata::_internal_set_sequence_number(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = value;
}

// bool is_handover_packet = 10;
inline void VehicleMetadata::clear_is_handover_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_handover_packet_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000800U);
}
inline bool VehicleMetadata::is_handover_packet() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.is_handover_packet)
  return _internal_is_handover_packet();
}
inline void VehicleMetadata::set_is_handover_packet(bool value) {
  _internal_set_is_handover_packet(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.is_handover_packet)
}
inline bool VehicleMetadata::_internal_is_handover_packet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_handover_packet_;
}
inline void VehicleMetadata::_internal_set_is_handover_packet(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_handover_packet_ = value;
}

// double vehicle_speed_kmh = 11;
inline void VehicleMetadata::clear_vehicle_speed_kmh() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_speed_kmh_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
}
inline double VehicleMetadata::vehicle_speed_kmh() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.vehicle_speed_kmh)
  return _internal_vehicle_speed_kmh();
}
inline void VehicleMetadata::set_vehicle_speed_kmh(double value) {
  _internal_set_vehicle_speed_kmh(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.vehicle_speed_kmh)
}
inline double VehicleMetadata::_internal_vehicle_speed_kmh() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vehicle_speed_kmh_;
}
inline void VehicleMetadata::_internal_set_vehicle_speed_kmh(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vehicle_speed_kmh_ = value;
}

// bool is_control_packet = 12;
inline void VehicleMetadata::clear_is_control_packet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_control_packet_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00001000U);
}
inline bool VehicleMetadata::is_control_packet() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.is_control_packet)
  return _internal_is_control_packet();
}
inline void VehicleMetadata::set_is_control_packet(bool value) {
  _internal_set_is_control_packet(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.is_control_packet)
}
inline bool VehicleMetadata::_internal_is_control_packet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_control_packet_;
}
inline void VehicleMetadata::_internal_set_is_control_packet(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_control_packet_ = value;
}

// int32 continuity_action = 13;
inline void VehicleMetadata::clear_continuity_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.continuity_action_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00004000U);
}
inline ::int32_t VehicleMetadata::continuity_action() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.continuity_action)
  return _internal_continuity_action();
}
inline void VehicleMetadata::set_continuity_action(::int32_t value) {
  _internal_set_continuity_action(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.continuity_action)
}
inline ::int32_t VehicleMetadata::_internal_continuity_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.continuity_action_;
}
inline void VehicleMetadata::_internal_set_continuity_action(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.continuity_action_ = value;
}

// string state_payload = 14;
inline void VehicleMetadata::clear_state_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& VehicleMetadata::state_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.state_payload)
  return _internal_state_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VehicleMetadata::set_state_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.state_payload_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.state_payload)
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::mutable_state_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_state_payload();
  // @@protoc_insertion_point(field_mutable:edgesim.VehicleMetadata.state_payload)
  return _s;
}
inline const ::std::string& VehicleMetadata::_internal_state_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_payload_.Get();
}
inline void VehicleMetadata::_internal_set_state_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VehicleMetadata::_internal_mutable_state_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.state_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VehicleMetadata::release_state_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:edgesim.VehicleMetadata.state_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.state_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.state_payload_.Set("", GetArena());
  }
  return released;
}
inline void VehicleMetadata::set_allocated_state_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.state_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.state_payload_.IsDefault()) {
    _impl_.state_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:edgesim.VehicleMetadata.state_payload)
}

// bool is_boundary_update = 15;
inline void VehicleMetadata::clear_is_boundary_update() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_boundary_update_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00002000U);
}
inline bool VehicleMetadata::is_boundary_update() const {
  // @@protoc_insertion_point(field_get:edgesim.VehicleMetadata.is_boundary_update)
  return _internal_is_boundary_update();
}
inline void VehicleMetadata::set_is_boundary_update(bool value) {
  _internal_set_is_boundary_update(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:edgesim.VehicleMetadata.is_boundary_update)
}
inline bool VehicleMetadata::_internal_is_boundary_update() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_boundary_update_;
}
inline void VehicleMetadata::_internal_set_is_boundary_update(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_boundary_update_ = value;
}

// -------------------------------------------------------------------

// ControllerCommand

// string command = 1;
inline void ControllerCommand::clear_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& ControllerCommand::command() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:edgesim.ControllerCommand.command)
  return _internal_command();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ControllerCommand::set_command(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.command_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:edgesim.ControllerCommand.command)
}
inline ::std::string* PROTOBUF_NONNULL ControllerCommand::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:edgesim.ControllerCommand.command)
  return _s;
}
inline const ::std::string& ControllerCommand::_internal_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_.Get();
}
inline void ControllerCommand::_internal_set_command(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ControllerCommand::_internal_mutable_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.command_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ControllerCommand::release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:edgesim.ControllerCommand.command)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.command_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.command_.Set("", GetArena());
  }
  return released;
}
inline void ControllerCommand::set_allocated_command(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.command_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:edgesim.ControllerCommand.command)
}

// double value = 2;
inline void ControllerCommand::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline double ControllerCommand::value() const {
  // @@protoc_insertion_point(field_get:edgesim.ControllerCommand.value)
  return _internal_value();
}
inline void ControllerCommand::set_value(double value) {
  _internal_set_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:edgesim.ControllerCommand.value)
}
inline double ControllerCommand::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void ControllerCommand::_internal_set_value(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// string fault_name = 3;
inline void ControllerCommand::clear_fault_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& ControllerCommand::fault_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:edgesim.ControllerCommand.fault_name)
  return _internal_fault_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ControllerCommand::set_fault_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.fault_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:edgesim.ControllerCommand.fault_name)
}
inline ::std::string* PROTOBUF_NONNULL ControllerCommand::mutable_fault_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_fault_name();
  // @@protoc_insertion_point(field_mutable:edgesim.ControllerCommand.fault_name)
  return _s;
}
inline const ::std::string& ControllerCommand::_internal_fault_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fault_name_.Get();
}
inline void ControllerCommand::_internal_set_fault_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fault_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ControllerCommand::_internal_mutable_fault_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.fault_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ControllerCommand::release_fault_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:edgesim.ControllerCommand.fault_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.fault_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fault_name_.Set("", GetArena());
  }
  return released;
}
inline void ControllerCommand::set_allocated_fault_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.fault_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fault_name_.IsDefault()) {
    _impl_.fault_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:edgesim.ControllerCommand.fault_name)
}

// bool enable = 4;
inline void ControllerCommand::clear_enable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline bool ControllerCommand::enable() const {
  // @@protoc_insertion_point(field_get:edgesim.ControllerCommand.enable)
  return _internal_enable();
}
inline void ControllerCommand::set_enable(bool value) {
  _internal_set_enable(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:edgesim.ControllerCommand.enable)
}
inline bool ControllerCommand::_internal_enable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_;
}
inline void ControllerCommand::_internal_set_enable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_ = value;
}

// int64 timestamp_ns = 5;
inline void ControllerCommand::clear_timestamp_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t ControllerCommand::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:edgesim.ControllerCommand.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void ControllerCommand::set_timestamp_ns(::int64_t value) {
  _internal_set_timestamp_ns(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:edgesim.ControllerCommand.timestamp_ns)
}
inline ::int64_t ControllerCommand::_internal_timestamp_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ns_;
}
inline void ControllerCommand::_internal_set_timestamp_ns(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ns_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace edgesim


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // custom_5fpayload_2eproto_2epb_2eh
