apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: edge-server-b
  template:
    metadata:
      labels:
        app: edge-server-b
    spec:
      containers:
      - name: server-b-container
        image: my_server_b:v9    
        imagePullPolicy: IfNotPresent     
        ports:
        - containerPort: 8080
          protocol: UDP  
---
apiVersion: v1
kind: Service
metadata:
  name: server-b-service
spec:
  type: LoadBalancer  
  selector:
    app: edge-server-b
  ports:
    - port: 8080        
      targetPort: 8080  
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server-a
  template:
    metadata:
      labels:
        app: edge-server-a
    spec:
      containers:
      - name: server-a-container
        image: my_server_a:v9    
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_B_HOST
          value: "server-b-service"