apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b-deployment
spec:
  replicas: 1  # Tells K8s to keep exactly 1 copy of Server B running
  selector:
    matchLabels:
      app: edge-server-b
  template:
    metadata:
      labels:
        app: edge-server-b
    spec:
      containers:
      - name: server-b-container
        image: my_server_b:v2      # Added :latest here
        imagePullPolicy: IfNotPresent  # Tells K8s to look for the image locally on your Mac
        ports:
        - containerPort: 8080
          protocol: UDP  # Crucial! Our socket is SOCK_DGRAM (UDP)
---
apiVersion: v1
kind: Service
metadata:
  name: server-b-service
spec:
  type: LoadBalancer  # Exposes the port directly to your Mac's localhost
  selector:
    app: edge-server-b
  ports:
    - port: 8080        # The port Server A will target
      targetPort: 8080  # The port Server B is listening on inside the container
      protocol: UDP